

services:
  # Service 1: Your Django Backend
  backend:
    build: ./Backend  # Path to the Dockerfile you just created
    container_name: mycalo_backend
    volumes:
      - ./Backend:/app  # Syncs your code so changes update instantly
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    environment:
      - DATABASE_PASSWORD=postgres
      
    depends_on:
      - db

  # Service 2: The Database (PostgreSQL)
  db:
    image: postgres:15
    container_name: mycalo_db
    environment:
      - POSTGRES_DB=mycalo_ai_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  # Service 3: NEW AI Service (FastAPI)
  ai_service:
    build: ./AI_Service
    container_name: mycalo_ai_service
    volumes:
      - ./AI_Service:/app  # Hot-reloading for development
    ports:
      - "8001:8001"
    env_file:
      - ./AI_Service/.env  # Make sure this file has your GEMINI_API_KEY
    # No depends_on needed for db (Stateless)

volumes:
  postgres_data: